{{- if and (not .Values.existingSecret) .Values.modelToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-model-token
  labels:
    {{- include "wordswarm.labels" . | nindent 4 }}
type: Opaque
stringData:
  MODEL_TOKEN: {{ .Values.modelToken | quote }}
{{- end }}
